baseURL = '/'
languageCode = 'fr-FR'
title = 'Hugo Cookbook Documentation'
themes = ['lotusdocs', "hugo-photoshop5-gallery"]
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
defaultContentLanguage = 'fr'

[params]

  [params.docs] 
    title = 'Hugo Cookbook Documentation'

    themeColor = "red"
    sidebarIcons    = true                                # enable sidebar icons? default false



[module]
  # uncomment line below for temporary local development of module,
  # when using a 'theme' as a git submodule or git cloned files
  replacements = "github.com/colinwilson/lotusdocs -> lotusdocs"
  [[module.imports]]
    path = "github.com/colinwilson/lotusdocs"
    disable = false
  [[module.imports]]
    path = "github.com/gohugoio/hugo-mod-bootstrap-scss/v5"
    disable = false
  [[module.imports]]
    path = "github.com/thkukuk/hugo-photoswipe5-gallery"
    disable = false
      
  [[module.imports]]
    path = 'github.com/hugomods/bootstrap'
  [[module.imports]]
    path = 'github.com/hugomods/images'
    disable = false